### ISSUE TITLE
[Actor/Menace sheet] The "Notes"tab is hidden when you open the window

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#141]
The "Notest tab of the actor sheet appears only when you widen the window to make the editable datas appear.
It's a pity, since this tab contains the description of the actor. Il would be very handy to be able to open the Notes without having to change the size of the window. it's something you can need when you play.
Whould it be possible to have the Notes tab available when the editable datas hare hidden?

<img width="788" alt="Capture d’écran 2022-05-13 à 10 29 16" src="https://user-images.githubusercontent.com/105451788/168243627-e2ab57cd-2391-4ccf-8aa8-0b64bf022e01.png">

**Comment by pemerson71** [comment]
The Threat sheet was made smaller to eliminate a problem with buttons extending all the way past the bottom of the sheet if it was scaled down.  The way it's scaled down, now, disallows any buttons to show until the creator lengthens the sheet.  Were there a way to stack buttons out to the side, in multiple columns, on one or both sides of the sheet, then increase the size of the sheet to something readily usable, I think that would be a lot better, but I don't know what level of work would be required to make that possible.

These buttons are arrayed around tokens instead of being on a single side, so I'm wondering if that could be done with the threat sheet, as well?

**Comment by Algor0113** [comment]
With the new charsheet, this issue is now obsolete
