### ISSUE TITLE
multiple armors shouldn't add their bonus 

### ISSUE THREAD

**Issue by rwanoux** [MetaMorphic-Digital/torgeternity#241]
as the title says

**Comment by Durak-Git** [comment]
I think they don't if the Effects is correctly bind to the armor itself.

The issue comes from Archetypes where some effects have no source
![image](https://user-images.githubusercontent.com/97435195/204514911-1f05832e-9c0b-4a46-bbf5-f7701d3a5d10.png)
Toggle the equip/unequipped modifies the effect's activity, but default state seems undefined (black hand, vs red hand (unequipped, and blue hand (equipped)) 
![image](https://user-images.githubusercontent.com/97435195/204515498-091479cc-0118-4863-9d02-65e6cd207a29.png)

Last time I used the equip/unequip toggle, or drag and drop a new armor on a sheet, the effect "transfered" by the item was correctly applied.
If manually created by a user in Actor effects , it's his duty to toggle which armor effect he has.

So only checking default configuration of Archetypes should solve the issue

**Comment by gmmatt** [comment]
I am closing this one for now.
