### ISSUE TITLE
Skill modifying Effects no longer function

### ISSUE THREAD

**Issue by SwordofSpirit** [MetaMorphic-Digital/torgeternity#268]
I'm not sure when this started, but today I noticed that Effects can no longer modify Skills or Defenses. They still work on Attributes and Armor. I haven't tested the other values.

It was only a few months ago that I made a bunch of effects (earlier this year), so they all have the latest data from [https://github.com/gmmatt/torgeternity/wiki/Storm-Knight-Data-Elements](url).

**Comment by Durak-Git** [comment]
Hello,
You're right, I'm preparing an update info for this in the wiki.
Due to computation with modified attributes, the ``.value`` can't be the targetted as modifier.
I suggest to modify the ``.adds`` instead
For defenses, it's the same, the right key to modify is adding ``Mod`` at the end ``system.dodgeDefenseMod``.

**Comment by Durak-Git** [comment]
For this, I think we just need to publish/update the next [available effects modifications](https://github.com/gmmatt/torgeternity/wiki/Storm-Knight-Data-Elements) in wiki
Helmut did some tests, at least one is inoperant (unarmed damage mod) that I must correct

**Comment by Algor0113** [comment]
As for now, we have the new wiki entry:

https://github.com/gmmatt/torgeternity/wiki/SK-Data-elements-after-3.0.4

Please check this out, it should be self-explainable :)
