### ISSUE TITLE
Custom Skills

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#38]
I am adding this one because it has been brought up at least twice, but I seem to recall that the TE designers are pretty adamant that no additional skills be included in the system. Am I wrong?

**Comment by pemerson71** [comment]
Different GMs are going to have their own viewpoints, different skills they want to add.  For me, the way I like to run games, there should be a Covert Ops skill, which is something I feel is absolutely missing from the way Torg: RPPW did things.  For RPPW I felt there was a very distinct Indiana Jones style sneaking around and figuring things out vibe which is VERY MUCH missing from Torg Eternity because someone at Ulisses determined it wasn't important; that was a definite swing and a miss.

However, I think the biggest problem with needing more skill spaces is for languages, professions, and Scholar skill.

**Comment by gmmatt** [comment]
Added in 2.3.0
