### ISSUE TITLE
Enforce maximum limits on attributes and skills

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#47]
In particular, racial maximums can be enforced.

**Comment by pemerson71** [comment]
Okay, I like the idea, but how and when?  Also, what about things like Mastery and Super-Attribute/Super-Skill?  How will those go into a system to release/reset those limitations?  The Foundry system of Active Effects is not nearly robust enough to allow something like this to take place; is that what you're waiting for with regards to this enhancement?

**Comment by Algor0113** [comment]
I also like the idea, but it has not come around since mentioned. For the time being, I'd close it down. We have possibilities to enter all the values we want, maybe in future we can still think about that when all the stuff we want to do is done and it's getting boring. Until then, this can be closed.
