### ISSUE TITLE
Update chat message on possibility/card/drama/...

### ISSUE THREAD

**Issue by orome70** [MetaMorphic-Digital/torgeternity#53]
**Situation**: when a character uses a possibility or other means to modify the result of his/her roll a **new** chat message is generated.

It seems that it would be **preferable** to **update** the original message with extra information.

In particular it would prevent a player to accidentally click on the "possibility" button of a previous roll.

**Comment by pemerson71** [comment]
I'm not saying mine are the only experiences, but in the two-and-a-half years since you wrote this message, I have to say none of my Players have had that problem.  Problems with accidentally discarding playing cards they wanted to keep -always their own fault- is far more prevalent than chat card issues.

Orome, what do you think... is this still an issue that needs to be addressed, or can it be closed?

**Comment by orome70** [comment]
Hi Paul!
Actually, this issue is labelled "enhancement", which means it is not really a bug, rather an idea for an improvement.
1) Updating chat message does not seem very difficult, several other game system do that (like wfrp).
2) At the moment when you use possibilities or other roll modifiers it generates plenty chat messages. Which clutter the chat log.
3) Updating the message would also enable to remove options that may only be used once per roll (like possibility or hero/drama cards)

It does not mean that it should have a very high priority, but I think it has a high ratio value/difficulty. :yum:

**Comment by Algor0113** [comment]
DOne with v3.1.0
