### ISSUE TITLE
special abilities

### ISSUE THREAD

**Issue by Vieux-troll** [MetaMorphic-Digital/torgeternity#62]
In the creation of special characters like elf edeinos I thought to create the night vision for example in the special abilities, but it seems that we can not attach it to a character sheet. Would it be possible to make it possible in a future update?

**Comment by pemerson71** [comment]
I have these acting more like Perks in my game, but I list them as (Racial), though I suppose they could be listed as _(Elf) Magical Affinity_ and stuff like that.  The larger problem I see is getting these Racial Perks to apply automatically on Race selection, then disappear if a Player makes a mistake or is generating a new Character and changes their mind, etc.  Active Effects would be built into these, as much as possible and, otherwise, noted as normal on the Character or Threat sheet.

**Comment by pemerson71** [comment]
This might need to be merged with another Issue -I'll look it up and post the link here in a minute- where races could be pulled over as items and plant all the bonuses and limitations of those races.  As for the truly strange edge-cases of multiple-race Characters, such as Elf-Edeinos, I'm thinking those will likely still need to be done on a case-by-case basis.

**Comment by Algor0113** [comment]
I've linked this to #52 as it would be a hole buffet of races (sounds awful out of a german mouth), but want to close down this issue as we don't need 2 of them, handling the same thing :)
