### ISSUE TITLE
1 Rolls Should Show a Failure...

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#69]
...and eliminate any ability to modify the roll.

**Comment by Durak-Git** [comment]
I think there's one exception : Active Defense.
As discussed, the rules excerpt you gave pointed that:

- "An active defense can't make a target more vulnerable, treat any bonus number less than +1 as a +1" was what we based that on."

- "Active Defense is not a test that can fail. It's just generating the bonus - therefore a roll of 1 on an AD is not "a natural roll of 1 on the first die roll when testing a skill or attribute total"

but

- Bad effects can still happen at GM's choice

(You can trigger disconnection, gain vulnerable, loose your weapon, etc.)
Right now, a 1-roll is Mishape and stop all (as you commented)

**Comment by pemerson71** [comment]
Is the roll modification made automatic or is this something GMs SHOULD be paying attention to?  Any time one of my Friends roll a 1, all of them know beyond the shadow of a doubt this is a mishap, and there is usually some sports-style reaction I have to pay attention to, in case I missed the roll, myself.  To be honest, instead of taking away abilities to control the roll through automation, make the word Mishap large and change from red to blue like the word Defenses does.  The code already exists and could be set up for Mishap, as well.

**Comment by Algor0113** [comment]
There are still some rules (like card treatment and other) that allows modifications though you've rolled a 1. Due to maintenance, closed this issue.
